version: '3.3'

services:
  skygear-server:
    env_file:
      - ./development.env
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data
  skygear-plugin:
    env_file:
      - ./development.env
    volumes:
      - .:/usr/src/app
  postgres:
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
